version: "3.9"  # optional since v1.27.0
services:
  server_rest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://octowink_auth_admin:root@postgres:5432/postgres
      PGRST_DB_SCHEMA: auth
      PGRST_DB_ANON_ROLE: octowink_auth_admin #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql

  auth:
    image: octowink/gotrue:1
    # build: .
    env_file:
      - dev.env
    ports:
      - "9999:9999"
    expose:
      - "9999"
    depends_on:
      - postgres

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3000/
    restart: always


  gateway:
    image: octowink/krakend:latest
    ports:
      - "8000:8000"
      - "8090:8090"

volumes:
  postgresql_data:
    driver: local
